/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tehtava9;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author denisbogdanov
 */
public class Teh9 extends javax.swing.JFrame {

    /**
     * Creates new form Teh9
     */
    public Teh9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jrd5 = new javax.swing.JRadioButton();
        jrd9 = new javax.swing.JRadioButton();
        jChkKinkku = new javax.swing.JCheckBox();
        jChkAnanas = new javax.swing.JCheckBox();
        jChkMeetwursti = new javax.swing.JCheckBox();
        jChkKana = new javax.swing.JCheckBox();
        jChkHerkkusieni = new javax.swing.JCheckBox();
        jChkAurajuusto = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtHinta = new javax.swing.JTextField();
        jtxtMaara = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtArea = new javax.swing.JTextArea();
        jtxtNormaali = new javax.swing.JTextField();
        jtxtPerhe = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pizzallaskuri");

        jLabel2.setText("Valitse koko, kappalemäärä ja täyttet, niin ohjelma laske hinnan pizzalle.   ");

        jLabel3.setText("Normaali ja perhepizzanhintaan kuuluu pohja, tomaattikastike ja juusto.  ");

        jLabel4.setText("Koko");

        jLabel5.setText("Täytteet");

        btnGroup.add(jrd5);
        jrd5.setText("Normaali:");
        jrd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrd5ActionPerformed(evt);
            }
        });

        btnGroup.add(jrd9);
        jrd9.setText("Perhe:");
        jrd9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrd9ActionPerformed(evt);
            }
        });

        jChkKinkku.setText("Kinkku + 0,70€");
        jChkKinkku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkKinkkuActionPerformed(evt);
            }
        });

        jChkAnanas.setText("Ananas + 0,50€");
        jChkAnanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkAnanasActionPerformed(evt);
            }
        });

        jChkMeetwursti.setText("Meetwursti + 0,50€");
        jChkMeetwursti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkMeetwurstiActionPerformed(evt);
            }
        });

        jChkKana.setText("Kana + 0,80€");
        jChkKana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkKanaActionPerformed(evt);
            }
        });

        jChkHerkkusieni.setText("Herkkusieni + 0,50€");
        jChkHerkkusieni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkHerkkusieniActionPerformed(evt);
            }
        });

        jChkAurajuusto.setText("Aurajuusto + 0,50€");
        jChkAurajuusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkAurajuustoActionPerformed(evt);
            }
        });

        jLabel6.setText("Hinta");

        jLabel7.setText("Määrä");

        jtxtHinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHintaActionPerformed(evt);
            }
        });

        jButton1.setText("Tilaa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtxtArea.setColumns(20);
        jtxtArea.setRows(5);
        jScrollPane1.setViewportView(jtxtArea);

        jtxtNormaali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNormaaliActionPerformed(evt);
            }
        });

        jtxtPerhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPerheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jChkKinkku)
                                .addComponent(jChkAnanas)
                                .addComponent(jChkMeetwursti)
                                .addComponent(jChkKana)
                                .addComponent(jChkHerkkusieni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jChkAurajuusto)
                                .addComponent(jtxtHinta)
                                .addComponent(jtxtMaara))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrd5)
                                    .addComponent(jrd9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtNormaali, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(jtxtPerhe))))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jrd5))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtNormaali, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPerhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrd9))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jChkKinkku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChkAnanas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChkMeetwursti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChkKana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChkHerkkusieni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChkAurajuusto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxtHinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrd5ActionPerformed
        // TODO add your handling code here:
        double price; // = Double.parseDouble(jtxtNormaali.getText());
        
        try {
        price = Double.parseDouble(jtxtNormaali.getText());
        }
        
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Vain hinta normalissa pizzassa, kiitos. Virhe: " + e.getMessage() , "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        }

        jtxtHinta.setText(String.valueOf(price));
        
        if(jChkKinkku.isSelected()) {
            price = price + 0.7;
            jtxtHinta.setText(String.valueOf(price));
        }else if (jChkAnanas.isSelected()){
            price = price + 0.50; 
            jtxtHinta.setText(String.valueOf(price));
        }else if (jChkMeetwursti.isSelected()){
            price = price + 0.50; 
            jtxtHinta.setText(String.valueOf(price));
        }else if (jChkKana.isSelected()){
            price = price + 0.80; 
            jtxtHinta.setText(String.valueOf(price));
        }else if (jChkHerkkusieni.isSelected()){
            price = price + 0.50; 
            jtxtHinta.setText(String.valueOf(price));
        }else if (jChkAurajuusto.isSelected()){
            price = price + 0.50; 
            jtxtHinta.setText(String.valueOf(price));
        } 
        jtxtHinta.setText(String.valueOf(price ));
    }//GEN-LAST:event_jrd5ActionPerformed

    private void jChkKinkkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkKinkkuActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(jtxtHinta.getText());

         if(jChkKinkku.isSelected()) {
            price = price + 0.7;
            jtxtHinta.setText(String.valueOf(price));
         } else {
             price = price - 0.7;
            jtxtHinta.setText(String.valueOf(price));
         }
    }//GEN-LAST:event_jChkKinkkuActionPerformed

    private void jtxtHintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHintaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtxtHintaActionPerformed

    private void jrd9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrd9ActionPerformed
        // TODO add your handling code here:
        double price; // = Double.parseDouble(jtxtNormaali.getText());
        
        try {
        price = Double.parseDouble(jtxtPerhe.getText());
        }
        
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Vain hinta perhen pizzassa. Virhe: " + e.getMessage() , "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        }          
        jtxtHinta.setText(String.valueOf(price));
        
        if(jChkKinkku.isSelected()) {
            price = price + 0.70;
            jtxtHinta.setText(String.valueOf(price));
        }else if (jChkAnanas.isSelected()){
            price = price + 0.50; 
            jtxtHinta.setText(String.valueOf(price));
        }else if (jChkMeetwursti.isSelected()){
            price = price + 0.50; 
            jtxtHinta.setText(String.valueOf(price));
        }else if (jChkKana.isSelected()){
            price = price + 0.80; 
            jtxtHinta.setText(String.valueOf(price));
        }else if (jChkHerkkusieni.isSelected()){
            price = price + 0.50; 
            jtxtHinta.setText(String.valueOf(price));
        }else if (jChkAurajuusto.isSelected()){
            price = price + 0.50; 
            jtxtHinta.setText(String.valueOf(price));
        }
        jtxtHinta.setText(String.valueOf(price ));
    }//GEN-LAST:event_jrd9ActionPerformed

    private void jChkAnanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkAnanasActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(jtxtHinta.getText());

         if(jChkAnanas.isSelected()) {
            price = price + 0.50;
            jtxtHinta.setText(String.valueOf(price));
         } else {
             price = price - 0.50;
            jtxtHinta.setText(String.valueOf(price));
         }

    }//GEN-LAST:event_jChkAnanasActionPerformed

    private void jChkMeetwurstiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkMeetwurstiActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(jtxtHinta.getText());

         if(jChkMeetwursti.isSelected()) {
            price = price + 0.50;
            jtxtHinta.setText(String.valueOf(price));
         } else {
             price = price - 0.50;
            jtxtHinta.setText(String.valueOf(price));
         }
    }//GEN-LAST:event_jChkMeetwurstiActionPerformed

    private void jChkKanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkKanaActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(jtxtHinta.getText());

         if(jChkKana.isSelected()) {
            price = price + 0.80;
            jtxtHinta.setText(String.valueOf(price));
         } else {
            price = price - 0.80; 
            jtxtHinta.setText(String.valueOf(price));
         }
    }//GEN-LAST:event_jChkKanaActionPerformed

    private void jChkHerkkusieniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkHerkkusieniActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(jtxtHinta.getText());

         if(jChkHerkkusieni.isSelected()) {
            price = price + 0.50;
            jtxtHinta.setText(String.valueOf(price));
         } else {
            price = price - 0.50;
            jtxtHinta.setText(String.valueOf(price));
         }

    }//GEN-LAST:event_jChkHerkkusieniActionPerformed

    private void jChkAurajuustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkAurajuustoActionPerformed
        // TODO add your handling code here:
        double price = Double.parseDouble(jtxtHinta.getText());

         if(jChkAurajuusto.isSelected()) {
            price = price + 0.50;
            jtxtHinta.setText(String.valueOf(price));
         } else {
             price = price - 0.50;
            jtxtHinta.setText(String.valueOf(price));
         }
    }//GEN-LAST:event_jChkAurajuustoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jrd5.setActionCommand("Normaalin pizza ");
        jrd9.setActionCommand("Perhen pizza ");
        double maara, tulos, price;
        price = Double.parseDouble(jtxtHinta.getText());

        try {
        maara = Double.parseDouble(jtxtMaara.getText());
        }
        
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Vain numeroita määrässä kiitos. Virhe: " + e.getMessage() , "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        }
        tulos = maara * price;
        if(btnGroup.getSelection().getActionCommand().equals("Normaalin pizza ")){
            String appendText = ("Valitsit: " + btnGroup.getSelection().getActionCommand()+"\n" + "Määrä: " + maara + " kpl" +"\n" + "Hintä: " + tulos + " €" +"\n"+"\n");
            jtxtArea.append(appendText);
        } else {
            String appendText = ("Valitsit: " + btnGroup.getSelection().getActionCommand()+"\n" + "Määrä: " + maara + " kpl" +"\n" + "Hintä: " + tulos + " €"+"\n"+"\n");
            jtxtArea.append(appendText);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtPerheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPerheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPerheActionPerformed

    private void jtxtNormaaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNormaaliActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtNormaaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teh9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teh9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teh9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teh9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teh9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jChkAnanas;
    private javax.swing.JCheckBox jChkAurajuusto;
    private javax.swing.JCheckBox jChkHerkkusieni;
    private javax.swing.JCheckBox jChkKana;
    private javax.swing.JCheckBox jChkKinkku;
    private javax.swing.JCheckBox jChkMeetwursti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrd5;
    private javax.swing.JRadioButton jrd9;
    private javax.swing.JTextArea jtxtArea;
    private javax.swing.JTextField jtxtHinta;
    private javax.swing.JTextField jtxtMaara;
    private javax.swing.JTextField jtxtNormaali;
    private javax.swing.JTextField jtxtPerhe;
    // End of variables declaration//GEN-END:variables
}
