/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 17479
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtPaiva = new javax.swing.JTextField();
        jcmbHoro = new javax.swing.JComboBox<>();
        jcboKuukausi = new javax.swing.JButton();
        jtxtTulos = new javax.swing.JLabel();
        jlblHorokooppi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ole hyvä ja anna syntymäpäiväsi ja valiset syntymäkuukautesti, niin kerron horoskooppisi");

        jLabel2.setText("Syntymäaika:");

        jLabel3.setText("Kuukausi:");

        jcmbHoro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tammikuu", "Helmikuu", "Maaliskuu", "Huhtikuu", "Toukokuu", "Kesäkuu", "Heinäkuu", "Eloku", "Syyskuu", "Lokakuu", "Marraskuu", "Joulukuu" }));
        jcmbHoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbHoroActionPerformed(evt);
            }
        });

        jcboKuukausi.setText("Horoskooppi");
        jcboKuukausi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboKuukausiActionPerformed(evt);
            }
        });

        jlblHorokooppi.setIcon(new javax.swing.ImageIcon("/Users/denisbogdanov/Desktop/Denis/Tieto ja viestenteknikka/Ohjelmointi/TMC NeatBeans/SwitchCase/Kauris.png")); // NOI18N

        jLabel4.setText("Horoskooppisi:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcmbHoro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtPaiva)
                                    .addComponent(jcboKuukausi, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtTulos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(13, 13, 13)
                        .addComponent(jlblHorokooppi, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtPaiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcmbHoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(jcboKuukausi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtTulos, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblHorokooppi, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbHoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbHoroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbHoroActionPerformed

    private void jcboKuukausiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboKuukausiActionPerformed
        // TODO add your handling code here:

        String kuukausi;
        kuukausi = (String)(jcmbHoro.getSelectedItem());
        double paiva = Double.parseDouble(jtxtPaiva.getText());
        
        switch (kuukausi) {
            case "Tammikuu":
                if(paiva>=1 && paiva<=20){
                jtxtTulos.setText("Kauris");
                
                    jtxtTulos.setText("Kauris");

                    jlblHorokooppi.setIcon(new javax.swing.ImageIcon(getClass().getResource("Kauris.png")));
                
                
                } else if(paiva>=21 && paiva<=31){
                jtxtTulos.setText( "Vesimies");
                }
            break;
            
            case "Helmikuu":
            if(paiva>=1 && paiva<=19){
                jtxtTulos.setText( "Vesimies");
                } else if(paiva>=20 && paiva<=28){
                jtxtTulos.setText( "Kalat");
                }
            break;

          case "Maaliskuu":
              if(paiva>=1 && paiva<=20){
                jtxtTulos.setText( "Kalat");
                } else if(paiva>=21 && paiva<=31){
                jtxtTulos.setText( "Oinas");
              }
            break;
          
            case "Huhtikuu":
                if(paiva>=1 && paiva<=19){
                jtxtTulos.setText( "Oinas");
                } else if(paiva>=20 && paiva<=30){
                jtxtTulos.setText( "Härkä");
                }
            break;
          case "Toukokuu":
            if(paiva>=1 && paiva<=21){
                jtxtTulos.setText( "Härkä");
                } else if(paiva>=22 && paiva<=31){
                jtxtTulos.setText( "Kaksonen");
                }
            break;
          case "Kesäkuu":
            if(paiva>=1 && paiva<=21){
                jtxtTulos.setText( "Kaksonen");
                } else if(paiva>=22 && paiva<=30){
                jtxtTulos.setText( "Rapu");
                }
            break;
          case "Heinakuu":
            if(paiva>=1 && paiva<=22){
                jtxtTulos.setText( "Rapu");
                } else if(paiva>=23 && paiva<=31){
                jtxtTulos.setText( "Leijona");
                }
            break;
            case "Elokuu":
            if(paiva>=1 && paiva<=22){
                jtxtTulos.setText( "Leijona");
                } else if(paiva>=23 && paiva<=31){
                jtxtTulos.setText( "Neitsyt");
                }
            break;
          case "Syyskuu":
            if(paiva>=1 && paiva<=23){
                jtxtTulos.setText( "Neitsyt");
                } else if(paiva>=24 && paiva<=30){
                jtxtTulos.setText( "Vaaka");
                }
            break;
          case "Lokakuu":
            if(paiva>=1 && paiva<=22){
                jtxtTulos.setText( "Vaaka");
                } else if(paiva>=23 && paiva<=31){
                jtxtTulos.setText( "Skorpioni");
                }
            break;
          case "Marraskuu":
            if(paiva>=1 && paiva<=22){
                jtxtTulos.setText( "Skorpioni");
                } else if(paiva>=23 && paiva<=30){
                jtxtTulos.setText( "Jousimies");
                }
            break;
          case "Joulukuu":
            if(paiva>=1 && paiva<=22){
                jtxtTulos.setText( "Jousimies");
                } else if(paiva>=23 && paiva<=31){
                jtxtTulos.setText( "Kauris");
                }
            break;
        }
    }//GEN-LAST:event_jcboKuukausiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jcboKuukausi;
    private javax.swing.JComboBox<String> jcmbHoro;
    private javax.swing.JLabel jlblHorokooppi;
    private javax.swing.JTextField jtxtPaiva;
    private javax.swing.JLabel jtxtTulos;
    // End of variables declaration//GEN-END:variables
}
