
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 17479
 */
public class Suorakaide extends javax.swing.JFrame {

    /**
     * Creates new form Suorakaide
     */
    public Suorakaide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtLaske = new javax.swing.JButton();
        jibiSelite = new javax.swing.JLabel();
        jtxtLeveys = new javax.swing.JTextField();
        jiblSelite = new javax.swing.JLabel();
        jbtnLabel2 = new javax.swing.JLabel();
        jtxtKorkeus = new javax.swing.JTextField();
        jtxtTulos = new javax.swing.JTextField();
        jlblLeveysvirhe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtLaske.setBackground(new java.awt.Color(255, 255, 51));
        jbtLaske.setForeground(new java.awt.Color(255, 51, 51));
        jbtLaske.setText("Laske");
        jbtLaske.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jbtLaskeMouseMoved(evt);
            }
        });
        jbtLaske.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jbtLaskeFocusLost(evt);
            }
        });
        jbtLaske.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLaskeActionPerformed(evt);
            }
        });

        jibiSelite.setText("Anna suorakaiteen leveys ja korkeus, lasken pinta-alan.");
        jibiSelite.setToolTipText("");

        jtxtLeveys.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jtxtLeveysMouseMoved(evt);
            }
        });
        jtxtLeveys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLeveysActionPerformed(evt);
            }
        });

        jiblSelite.setText("Leveys(m)");

        jbtnLabel2.setText("Korkeus");

        jtxtKorkeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtKorkeusActionPerformed(evt);
            }
        });

        jtxtTulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTulosActionPerformed(evt);
            }
        });

        jlblLeveysvirhe.setText("FORA");
        jlblLeveysvirhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblLeveysvirheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtTulos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jiblSelite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(jbtnLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtKorkeus, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtLaske, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtLeveys, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(jlblLeveysvirhe))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jibiSelite, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jibiSelite)
                .addGap(18, 18, 18)
                .addComponent(jiblSelite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtLeveys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbtnLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtKorkeus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblLeveysvirhe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtLaske)
                .addGap(18, 18, 18)
                .addComponent(jtxtTulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtLaskeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLaskeActionPerformed
        // TODO add your handling code here:
        double leveys, korkeus, tulos;
        
        try {
            
        leveys = Double.parseDouble(jtxtLeveys.getText());
        korkeus = Double.parseDouble(jtxtKorkeus.getText());    
        }
        
        catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vain numeroita leveys kentässä kiitos. Virhe: " + e.getMessage() , "Virhe", JOptionPane.ERROR_MESSAGE);
        jlblLeveysvirhe.setForeground(Color.red);
        jlblLeveysvirhe.setText("Virhe leveydessä. Oleppas tarkkana!");
        jlblLeveysvirhe.setVisible(true);
        return;
        }
        
        jlblLeveysvirhe.setVisible(false);
        if(leveys<=0 || korkeus <=0){
                    JOptionPane.showMessageDialog(null, "Luvut oltava positiivisia! Kiitos. Virhe: ");
                    return;
        } else if (leveys >=0 || korkeus >=0) {
            tulos = korkeus*leveys; 
        jtxtTulos.setText(String.valueOf(tulos));}
    }//GEN-LAST:event_jbtLaskeActionPerformed

    private void jtxtLeveysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLeveysActionPerformed
        float leveys, korkeus, tulos;
        
        try {
            
        leveys = Float.parseFloat(jtxtLeveys.getText());
        }
        
        catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vain numeroita leveys kentässä kiitos. Virhe: " + e.getMessage() , "Virhe", JOptionPane.ERROR_MESSAGE);
        jlblLeveysvirhe.setForeground(Color.red);
        jlblLeveysvirhe.setText("Virhe leveydessä. Oleppas tarkkana!");
        jlblLeveysvirhe.setVisible(true);

        return;
                }
        
        jlblLeveysvirhe.setVisible(false);
        if(leveys<=0){
                    JOptionPane.showMessageDialog(null, "Luvut oltava positiivisia! Kiitos. Virhe: ");
                    return;
        }
    }//GEN-LAST:event_jtxtLeveysActionPerformed

    private void jtxtKorkeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtKorkeusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtKorkeusActionPerformed

    private void jtxtTulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTulosActionPerformed
        // TODO add your handling code here:
        
        Double pintaala, leveys, korkeus;
        
        leveys=Double.parseDouble(jtxtLeveys.getText());
        korkeus=Double.parseDouble(jtxtKorkeus.getText());
        
        //laske tai pinta ala
        pintaala=leveys*korkeus;
        
        jtxtTulos.setText(String.valueOf(pintaala));
    }//GEN-LAST:event_jtxtTulosActionPerformed

    private void jtxtLeveysMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLeveysMouseMoved
        
        
        //  JOptionPane.showMessageDialog(null, "hiiren liikutusdemo", "demo", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jtxtLeveysMouseMoved

    private void jlblLeveysvirheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblLeveysvirheActionPerformed
        // TODO add your handling code here:
        int i =0;
        int summa =0;
        
        for(i=0; i<10; i++){
            summa=+i;
        }
    }//GEN-LAST:event_jlblLeveysvirheActionPerformed

    private void jbtLaskeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jbtLaskeFocusLost
        // TODO add your handling code here:
        
       // JOptionPane.showMessageDialog(null, "Poistut leveys kentästä toivottavasti annoit leveyden oikein eli ei kirjaimia ym. erikoismerkkejä");
    }//GEN-LAST:event_jbtLaskeFocusLost

    private void jbtLaskeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtLaskeMouseMoved
        // TODO add your handling code here:
       // JOptionPane.showMessageDialog(null, "liikutit hiirtä");
    }//GEN-LAST:event_jbtLaskeMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Suorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Suorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Suorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Suorakaide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Suorakaide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtLaske;
    private javax.swing.JLabel jbtnLabel2;
    private javax.swing.JLabel jibiSelite;
    private javax.swing.JLabel jiblSelite;
    private javax.swing.JButton jlblLeveysvirhe;
    private javax.swing.JTextField jtxtKorkeus;
    private javax.swing.JTextField jtxtLeveys;
    private javax.swing.JTextField jtxtTulos;
    // End of variables declaration//GEN-END:variables
}
