/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tehtava2;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author 17479
 */
public class New extends javax.swing.JFrame {

    /**
     * Creates new form New
     */
    public New() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtEtunimi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtnTarkista = new javax.swing.JButton();
        jtxtIka = new javax.swing.JTextField();
        jlblTulos = new javax.swing.JLabel();
        jlblNimivirhe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kerrotko nimesi ja ikä");

        jtxtEtunimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEtunimiActionPerformed(evt);
            }
        });

        jLabel2.setText("Etunimi:");

        jLabel3.setText("Ikä:");

        jbtnTarkista.setText("Tarkista");
        jbtnTarkista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTarkistaActionPerformed(evt);
            }
        });

        jtxtIka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIkaActionPerformed(evt);
            }
        });

        jlblNimivirhe.setText("Button");
        jlblNimivirhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblNimivirheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtEtunimi, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jtxtIka)
                            .addComponent(jbtnTarkista))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jlblNimivirhe)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtEtunimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtIka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTarkista)
                    .addComponent(jlblNimivirhe))
                .addGap(18, 18, 18)
                .addComponent(jlblTulos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtEtunimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEtunimiActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jtxtEtunimiActionPerformed

    private void jbtnTarkistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTarkistaActionPerformed
        // TODO add your handling code here:
        
        String nimi; 
        double ika;
        String tulos;
        double nimiika;

        ika = Double.parseDouble(jtxtIka.getText());
        nimi = jtxtEtunimi.getText();

        if(ika<=17){
            tulos = nimi + ", olet alle 18-vuotias. Tervetuloa ravintolaamme kun olet täyttänyt 18.";
        } else {
            tulos="Tervetuloa ravintolaamme:" + nimi + "(olet täysi-ikäinen)";
        }
    
        jlblTulos.setText(String.valueOf(tulos));  
        
        try{
                    nimiika = Double.parseDouble(jtxtEtunimi.getText());
                    JOptionPane.showMessageDialog(null, "Nimessä ei saa olla numeroita: " , "Virhe", JOptionPane.ERROR_MESSAGE);
                    return;
        } catch (NumberFormatException e) {
              
        }
        try {
       
        ika = Double.parseDouble(jtxtIka.getText());
        nimi = jtxtEtunimi.getText();
        }
        
        catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vain numeroita leveys kentässä kiitos. Virhe: " + e.getMessage() , "Virhe", JOptionPane.ERROR_MESSAGE);
        jlblNimivirhe.setForeground(Color.blue);
        jlblNimivirhe.setText("Virhe leveydessä. Oleppas tarkkana!");
        jlblNimivirhe.setVisible(true);
        return;
        }
        
        jlblNimivirhe.setVisible(false);
        if(ika<=17){
            tulos = nimi + ", olet alle 18-vuotias. Tervetuloa ravintolaamme kun olet täyttänyt 18.";
        } else {
            tulos="Tervetuloa ravintolaamme:" + nimi + "(olet täysi-ikäinen)";
        }

    }//GEN-LAST:event_jbtnTarkistaActionPerformed

    private void jlblNimivirheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblNimivirheActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jlblNimivirheActionPerformed

    private void jtxtIkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIkaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtnTarkista;
    private javax.swing.JButton jlblNimivirhe;
    private javax.swing.JLabel jlblTulos;
    private javax.swing.JTextField jtxtEtunimi;
    private javax.swing.JTextField jtxtIka;
    // End of variables declaration//GEN-END:variables
}
