/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tehtava10;

import javax.swing.JOptionPane;

/**
 *
 * @author denisbogdanov
 */
public class Teh10 extends javax.swing.JFrame {

    /**
     * Creates new form Teh10
     */
    public Teh10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNimi = new javax.swing.JTextField();
        jtxtSukunimi = new javax.swing.JTextField();
        jchc2 = new javax.swing.JCheckBox();
        jchc1 = new javax.swing.JCheckBox();
        jchc3 = new javax.swing.JCheckBox();
        jchc4 = new javax.swing.JCheckBox();
        jchc7 = new javax.swing.JCheckBox();
        jchc5 = new javax.swing.JCheckBox();
        jchc6 = new javax.swing.JCheckBox();
        jchc11 = new javax.swing.JCheckBox();
        jchc14 = new javax.swing.JCheckBox();
        jchc12 = new javax.swing.JCheckBox();
        jchc13 = new javax.swing.JCheckBox();
        jchc9 = new javax.swing.JCheckBox();
        jchc8 = new javax.swing.JCheckBox();
        jchc10 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jspr2 = new javax.swing.JSpinner();
        jspr1 = new javax.swing.JSpinner();
        jspr14 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jspr3 = new javax.swing.JSpinner();
        jspr4 = new javax.swing.JSpinner();
        jspr7 = new javax.swing.JSpinner();
        jspr6 = new javax.swing.JSpinner();
        jspr5 = new javax.swing.JSpinner();
        jspr9 = new javax.swing.JSpinner();
        jspr8 = new javax.swing.JSpinner();
        jspr10 = new javax.swing.JSpinner();
        jspr11 = new javax.swing.JSpinner();
        jspr13 = new javax.swing.JSpinner();
        jspr12 = new javax.swing.JSpinner();
        jtxtMaara = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jtxtHinta = new javax.swing.JTextField();
        jtxtPrice2 = new javax.swing.JTextField();
        jtxtPrice3 = new javax.swing.JTextField();
        jtxtPrice4 = new javax.swing.JTextField();
        jtxtPrice1 = new javax.swing.JTextField();
        jtxtPrice5 = new javax.swing.JTextField();
        jtxtPrice6 = new javax.swing.JTextField();
        jtxtPrice7 = new javax.swing.JTextField();
        jtxtPrice9 = new javax.swing.JTextField();
        jtxtPrice10 = new javax.swing.JTextField();
        jtxtPrice11 = new javax.swing.JTextField();
        jtxtPrice8 = new javax.swing.JTextField();
        jtxtPrice12 = new javax.swing.JTextField();
        jtxtPrice13 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Etunimi:");

        jLabel2.setText("Sukunimi:");

        jtxtSukunimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSukunimiActionPerformed(evt);
            }
        });

        jchc2.setText("Lapset 15 eur");
        jchc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc2ActionPerformed(evt);
            }
        });

        jchc1.setText("Aikuiset 25 eur  ");
        jchc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc1ActionPerformed(evt);
            }
        });

        jchc3.setText("Lyhyet 0 eur ");
        jchc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc3ActionPerformed(evt);
            }
        });

        jchc4.setText("Keskipitkät 5 eur  ");
        jchc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc4ActionPerformed(evt);
            }
        });

        jchc7.setText("Tyviväri 30 eur  ");
        jchc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc7ActionPerformed(evt);
            }
        });

        jchc5.setText("Pitkät 10 eur  ");
        jchc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc5ActionPerformed(evt);
            }
        });

        jchc6.setText("Raidat 3o eur  ");
        jchc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc6ActionPerformed(evt);
            }
        });

        jchc11.setText("Pesu 10 eur");
        jchc11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc11ActionPerformed(evt);
            }
        });

        jchc14.setText("5 eur alennuksen*");
        jchc14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc14ActionPerformed(evt);
            }
        });

        jchc12.setText("Kiharrus 15 eur");
        jchc12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc12ActionPerformed(evt);
            }
        });

        jchc13.setText("Permanentti 50 eur");
        jchc13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc13ActionPerformed(evt);
            }
        });

        jchc9.setText("Juhlakampaus 50 eur");
        jchc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc9ActionPerformed(evt);
            }
        });

        jchc8.setText("Koko pään värjäys 80 eur  ");
        jchc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc8ActionPerformed(evt);
            }
        });

        jchc10.setText("Koekampaus 20 eur");
        jchc10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchc10ActionPerformed(evt);
            }
        });

        jLabel3.setText("* - Internet-varauksella saa - 5 eur alennuksen, jos ssumma on 25 eur tai enemmän");

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        jspr2.setModel(new javax.swing.SpinnerNumberModel(1, 0, 10, 1));
        jspr2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr2StateChanged(evt);
            }
        });

        jspr1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jspr1AncestorRemoved(evt);
            }
        });
        jspr1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr1StateChanged(evt);
            }
        });
        jspr1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jspr1ComponentMoved(evt);
            }
        });

        jspr14.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1, 1));

        jLabel4.setText("Määrä:");

        jspr3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr3StateChanged(evt);
            }
        });

        jspr4.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr4StateChanged(evt);
            }
        });

        jspr7.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr7StateChanged(evt);
            }
        });

        jspr6.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr6StateChanged(evt);
            }
        });

        jspr5.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr5StateChanged(evt);
            }
        });

        jspr9.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr9StateChanged(evt);
            }
        });

        jspr8.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr8StateChanged(evt);
            }
        });

        jspr10.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr10StateChanged(evt);
            }
        });

        jspr11.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr11StateChanged(evt);
            }
        });

        jspr13.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr13.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr13StateChanged(evt);
            }
        });

        jspr12.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        jspr12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspr12StateChanged(evt);
            }
        });

        jtxtMaara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMaaraActionPerformed(evt);
            }
        });

        jButton1.setText("Tilaa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Poista");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtxtHinta.setText("0");
        jtxtHinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHintaActionPerformed(evt);
            }
        });

        jtxtPrice2.setText("0");
        jtxtPrice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice2ActionPerformed(evt);
            }
        });

        jtxtPrice3.setText("0");
        jtxtPrice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice3ActionPerformed(evt);
            }
        });

        jtxtPrice4.setText("0");
        jtxtPrice4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice4ActionPerformed(evt);
            }
        });

        jtxtPrice1.setText("0");
        jtxtPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice1ActionPerformed(evt);
            }
        });

        jtxtPrice5.setText("0");
        jtxtPrice5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice5ActionPerformed(evt);
            }
        });

        jtxtPrice6.setText("0");
        jtxtPrice6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice6ActionPerformed(evt);
            }
        });

        jtxtPrice7.setText("0");
        jtxtPrice7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice7ActionPerformed(evt);
            }
        });

        jtxtPrice9.setText("0");
        jtxtPrice9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice9ActionPerformed(evt);
            }
        });

        jtxtPrice10.setText("0");
        jtxtPrice10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice10ActionPerformed(evt);
            }
        });

        jtxtPrice11.setText("0");
        jtxtPrice11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice11ActionPerformed(evt);
            }
        });

        jtxtPrice8.setText("0");
        jtxtPrice8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice8ActionPerformed(evt);
            }
        });

        jtxtPrice12.setText("0");
        jtxtPrice12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice12ActionPerformed(evt);
            }
        });

        jtxtPrice13.setText("0");
        jtxtPrice13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrice13ActionPerformed(evt);
            }
        });

        jButton3.setText("Laske hinta:");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jspr9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jspr8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jspr11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jspr10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jspr13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jspr12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jspr14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jchc9)
                                            .addComponent(jchc8)
                                            .addComponent(jchc10)
                                            .addComponent(jchc11)
                                            .addComponent(jchc12)
                                            .addComponent(jchc13)
                                            .addComponent(jchc14)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(264, 264, 264)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtPrice13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtPrice12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtPrice10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtPrice11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtPrice9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxtPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jspr7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jspr5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jspr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jspr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jspr4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jspr3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jspr6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jchc6)
                                            .addComponent(jchc5)
                                            .addComponent(jchc7))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jtxtPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtxtPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtxtPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jchc1)
                                            .addComponent(jchc2)
                                            .addComponent(jchc4)
                                            .addComponent(jchc3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtxtPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtxtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtHinta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtxtSukunimi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(23, 23, 23)
                                .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtSukunimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtMaara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jspr8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jchc8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jspr9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jchc9))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jspr10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jchc10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jspr11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jchc11))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jspr13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jchc13)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jspr12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jchc12))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtPrice8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtPrice9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jtxtPrice10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtPrice11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jtxtPrice13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtxtPrice12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jspr14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchc14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jspr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchc1)
                            .addComponent(jtxtPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jspr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchc2)
                            .addComponent(jtxtPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jspr3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchc3)
                            .addComponent(jtxtPrice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jspr4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchc4)
                            .addComponent(jtxtPrice4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jspr6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jchc6)
                                    .addComponent(jtxtPrice6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jspr7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jchc7)
                                    .addComponent(jtxtPrice7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jspr5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jchc5)
                                .addComponent(jtxtPrice5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtHinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jchc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc2ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice2.getText());
        spinner = (Integer)jspr2.getValue();
        luku = 15;
        
        if(jchc2.isSelected()) {
            price = luku * spinner;
            jtxtPrice2.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice2.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc2ActionPerformed

    private void jchc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc4ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice4.getText());
        spinner = (Integer)jspr4.getValue();
        luku = 5;
        
        if(jchc4.isSelected()) {
            price = luku * spinner;
            jtxtPrice4.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice4.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc4ActionPerformed

    private void jchc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc1ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice1.getText());
        spinner = (Integer)jspr1.getValue();
        luku = 25;
        
        if(jchc1.isSelected()) {
            price = luku * spinner;
            jtxtPrice1.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice1.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc1ActionPerformed

    private void jchc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc5ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice5.getText());
        spinner = (Integer)jspr5.getValue();
        luku = 10;
        
        if(jchc5.isSelected()) {
            price = luku * spinner;
            jtxtPrice5.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice5.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc5ActionPerformed

    private void jchc11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc11ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice11.getText());
        spinner = (Integer)jspr11.getValue();
        luku = 10;
        
        if(jchc11.isSelected()) {
            price = luku * spinner;
            jtxtPrice11.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice11.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc11ActionPerformed

    private void jchc13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc13ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice13.getText());
        spinner = (Integer)jspr13.getValue();
        luku = 50;
        
        if(jchc13.isSelected()) {
            price = luku * spinner;
            jtxtPrice13.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice13.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc13ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        textArea.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jspr1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr1StateChanged
        //jchc1.setText(jspr1.getValue().toString());
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice1.getText());
        aikuisetSpinner = (Integer)jspr1.getValue();
        aikuiset = 25;
        
        if(jchc1.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice1.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice1.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr1StateChanged

    private void jspr1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jspr1ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jspr1ComponentMoved

    private void jspr1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jspr1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jspr1AncestorRemoved

    private void jtxtHintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHintaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHintaActionPerformed

    private void jchc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc3ActionPerformed
        // TODO add your handling code here:
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice3.getText());
        spinner = (Integer)jspr3.getValue();
        luku = 0;
        
        if(jchc3.isSelected()) {
            price = luku * spinner;
            jtxtPrice3.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice3.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc3ActionPerformed

    private void jchc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc6ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice6.getText());
        spinner = (Integer)jspr6.getValue();
        luku = 30;
        
        if(jchc6.isSelected()) {
            price = luku * spinner;
            jtxtPrice6.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice6.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc6ActionPerformed

    private void jchc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc7ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice7.getText());
        spinner = (Integer)jspr7.getValue();
        luku = 30;
        
        if(jchc7.isSelected()) {
            price = luku * spinner;
            jtxtPrice7.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice7.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc7ActionPerformed

    private void jchc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc8ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice8.getText());
        spinner = (Integer)jspr8.getValue();
        luku = 80;
        
        if(jchc8.isSelected()) {
            price = luku * spinner;
            jtxtPrice8.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice8.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc8ActionPerformed

    private void jchc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc9ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice9.getText());
        spinner = (Integer)jspr9.getValue();
        luku = 50;
        
        if(jchc9.isSelected()) {
            price = luku * spinner;
            jtxtPrice9.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice9.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc9ActionPerformed

    private void jchc10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc10ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice10.getText());
        spinner = (Integer)jspr10.getValue();
        luku = 20;
        
        if(jchc10.isSelected()) {
            price = luku * spinner;
            jtxtPrice10.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice10.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc10ActionPerformed

    private void jchc12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc12ActionPerformed
        int price, luku, spinner;
        price = Integer.parseInt(jtxtPrice12.getText());
        spinner = (Integer)jspr12.getValue();
        luku = 15;
        
        if(jchc12.isSelected()) {
            price = luku * spinner;
            jtxtPrice12.setText(String.valueOf(price));
        }  else {
            price = price-(luku * spinner);
            jtxtPrice12.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc12ActionPerformed

    private void jchc14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchc14ActionPerformed
        // TODO add your handling code here:
        int price, luku, spinner;
        price = Integer.parseInt(jtxtHinta.getText());
        spinner = (Integer)jspr14.getValue();
        luku = 5;
        
        if(jchc14.isSelected()) {
            price = price - luku;
            jtxtHinta.setText(String.valueOf(price));
        } else {
            price = price + luku;
            jtxtHinta.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jchc14ActionPerformed

    private void jspr2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr2StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice2.getText());
        aikuisetSpinner = (Integer)jspr2.getValue();
        aikuiset = 15;
        
        if(jchc2.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice2.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice2.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr2StateChanged

    private void jtxtPrice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice2ActionPerformed

    private void jtxtPrice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice3ActionPerformed

    private void jtxtPrice4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice4ActionPerformed

    private void jtxtPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice1ActionPerformed

    private void jtxtPrice5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice5ActionPerformed

    private void jtxtPrice6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice6ActionPerformed

    private void jtxtPrice7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice7ActionPerformed

    private void jtxtPrice9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice9ActionPerformed

    private void jtxtPrice10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice10ActionPerformed

    private void jtxtPrice11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice11ActionPerformed

    private void jtxtPrice8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice8ActionPerformed

    private void jtxtPrice12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice12ActionPerformed

    private void jtxtPrice13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrice13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrice13ActionPerformed

    private void jspr3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr3StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice3.getText());
        aikuisetSpinner = (Integer)jspr3.getValue();
        aikuiset = 0;
        
        if(jchc3.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice3.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice3.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr3StateChanged

    private void jspr4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr4StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice4.getText());
        aikuisetSpinner = (Integer)jspr4.getValue();
        aikuiset = 5;
        
        if(jchc4.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice4.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice4.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr4StateChanged

    private void jspr5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr5StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice5.getText());
        aikuisetSpinner = (Integer)jspr5.getValue();
        aikuiset = 10;
        
        if(jchc5.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice5.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice5.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr5StateChanged

    private void jspr6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr6StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice6.getText());
        aikuisetSpinner = (Integer)jspr6.getValue();
        aikuiset = 30;
        
        if(jchc6.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice6.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice6.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr6StateChanged

    private void jspr7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr7StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice7.getText());
        aikuisetSpinner = (Integer)jspr7.getValue();
        aikuiset = 30;
        
        if(jchc7.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice7.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice7.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr7StateChanged

    private void jspr8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr8StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice8.getText());
        aikuisetSpinner = (Integer)jspr8.getValue();
        aikuiset = 80;
        
        if(jchc8.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice8.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice8.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr8StateChanged

    private void jspr9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr9StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice9.getText());
        aikuisetSpinner = (Integer)jspr9.getValue();
        aikuiset = 50;
        
        if(jchc9.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice9.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice9.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr9StateChanged

    private void jspr10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr10StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice10.getText());
        aikuisetSpinner = (Integer)jspr10.getValue();
        aikuiset = 20;
        
        if(jchc10.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice10.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice10.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr10StateChanged

    private void jspr11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr11StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice11.getText());
        aikuisetSpinner = (Integer)jspr11.getValue();
        aikuiset = 10;
        
        if(jchc11.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice11.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice11.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr11StateChanged

    private void jspr12StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr12StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice12.getText());
        aikuisetSpinner = (Integer)jspr12.getValue();
        aikuiset = 15;
        
        if(jchc12.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice12.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice12.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr12StateChanged

    private void jspr13StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspr13StateChanged
        int price, aikuiset, aikuisetSpinner;
        price = Integer.parseInt(jtxtPrice13.getText());
        aikuisetSpinner = (Integer)jspr13.getValue();
        aikuiset = 50;
        
        if(jchc13.isSelected()) {
            price = aikuiset * aikuisetSpinner;
            jtxtPrice13.setText(String.valueOf(price));
        }  else {
            price = price;
            jtxtPrice13.setText(String.valueOf(price));
        }
    }//GEN-LAST:event_jspr13StateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int price1, price2, price3, price4, price5, price6, price7, price8, price9, price10, price11, price12, price13, 
                summa, maara, marTarkista;
        double nimiika, ikanimi;
        try {
        marTarkista = Integer.parseInt(jtxtMaara.getText());
        }
        
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Vain numeroita määrässä kiitos. Virhe: " + e.getMessage() , "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            nimiika = Double.parseDouble(jtxtNimi.getText());
            JOptionPane.showMessageDialog(null, "Nimessä ei saa olla numeroita: " , "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        catch (NumberFormatException e) {      
        }
        try{
                        
            ikanimi = Double.parseDouble(jtxtSukunimi.getText());
            JOptionPane.showMessageDialog(null, "Sukunimissa ei saa olla numeroita: " , "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        catch (NumberFormatException e) {      
        }

        maara = Integer.parseInt(jtxtMaara.getText());
        price1 = Integer.parseInt(jtxtPrice1.getText());
        price2 = Integer.parseInt(jtxtPrice2.getText());
        price3 = Integer.parseInt(jtxtPrice3.getText());
        price4 = Integer.parseInt(jtxtPrice4.getText());
        price5 = Integer.parseInt(jtxtPrice5.getText());
        price6 = Integer.parseInt(jtxtPrice6.getText());
        price7 = Integer.parseInt(jtxtPrice7.getText());
        price8 = Integer.parseInt(jtxtPrice8.getText());
        price9 = Integer.parseInt(jtxtPrice9.getText());
        price10 = Integer.parseInt(jtxtPrice10.getText());
        price11 = Integer.parseInt(jtxtPrice11.getText());
        price12 = Integer.parseInt(jtxtPrice12.getText());
        price13 = Integer.parseInt(jtxtPrice13.getText());
        summa = (price1+price2+price3+price4+price5+price6+price7+price8+price9+price10+price11+price12+price13)*maara;
        jtxtHinta.setText(String.valueOf(summa));

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nimi, sukunimi, ihm;
        int maara, hinta;
        nimi = jtxtNimi.getText();
        sukunimi = jtxtSukunimi.getText();
        maara = Integer.parseInt(jtxtMaara.getText());
        hinta = Integer.parseInt(jtxtHinta.getText());
        if(maara>1){
            ihm="ihmiset";
        }else{
            ihm="ihminen";
        }

        
        String appendText = ("Asiakas: " + nimi + " " + sukunimi + "\n" + "Määrä: " + maara + ihm +"\n" 
                + "Hintä: " + hinta + " €" +"\n"+"\n");
        textArea.append(appendText);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtMaaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMaaraActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtMaaraActionPerformed

    private void jtxtSukunimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSukunimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSukunimiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teh10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teh10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teh10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teh10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teh10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jchc1;
    private javax.swing.JCheckBox jchc10;
    private javax.swing.JCheckBox jchc11;
    private javax.swing.JCheckBox jchc12;
    private javax.swing.JCheckBox jchc13;
    private javax.swing.JCheckBox jchc14;
    private javax.swing.JCheckBox jchc2;
    private javax.swing.JCheckBox jchc3;
    private javax.swing.JCheckBox jchc4;
    private javax.swing.JCheckBox jchc5;
    private javax.swing.JCheckBox jchc6;
    private javax.swing.JCheckBox jchc7;
    private javax.swing.JCheckBox jchc8;
    private javax.swing.JCheckBox jchc9;
    private javax.swing.JSpinner jspr1;
    private javax.swing.JSpinner jspr10;
    private javax.swing.JSpinner jspr11;
    private javax.swing.JSpinner jspr12;
    private javax.swing.JSpinner jspr13;
    private javax.swing.JSpinner jspr14;
    private javax.swing.JSpinner jspr2;
    private javax.swing.JSpinner jspr3;
    private javax.swing.JSpinner jspr4;
    private javax.swing.JSpinner jspr5;
    private javax.swing.JSpinner jspr6;
    private javax.swing.JSpinner jspr7;
    private javax.swing.JSpinner jspr8;
    private javax.swing.JSpinner jspr9;
    private javax.swing.JTextField jtxtHinta;
    private javax.swing.JTextField jtxtMaara;
    private javax.swing.JTextField jtxtNimi;
    private javax.swing.JTextField jtxtPrice1;
    private javax.swing.JTextField jtxtPrice10;
    private javax.swing.JTextField jtxtPrice11;
    private javax.swing.JTextField jtxtPrice12;
    private javax.swing.JTextField jtxtPrice13;
    private javax.swing.JTextField jtxtPrice2;
    private javax.swing.JTextField jtxtPrice3;
    private javax.swing.JTextField jtxtPrice4;
    private javax.swing.JTextField jtxtPrice5;
    private javax.swing.JTextField jtxtPrice6;
    private javax.swing.JTextField jtxtPrice7;
    private javax.swing.JTextField jtxtPrice8;
    private javax.swing.JTextField jtxtPrice9;
    private javax.swing.JTextField jtxtSukunimi;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
