/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tehtava5;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author 17479
 */
public class NewJFrame5 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame5
     */
    public NewJFrame5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtNimi = new javax.swing.JTextField();
        jtxtIka = new javax.swing.JTextField();
        jbtnTervehdys = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlstReded = new javax.swing.JList<>();
        jlblBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ole hyvä ja anna nimesi ja ikäsi vuosina.");

        jLabel2.setText("Nimi:");

        jLabel3.setText("Ikä:");

        jtxtIka.setToolTipText("");

        jbtnTervehdys.setText("Tervehdys");
        jbtnTervehdys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTervehdysActionPerformed(evt);
            }
        });

        jlstReded.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jScrollPane1.setViewportView(jlstReded);

        jlblBtn.setText("Button");
        jlblBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlblBtnActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtNimi, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jtxtIka))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jbtnTervehdys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblBtn)
                .addGap(137, 137, 137))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtIka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTervehdys)
                    .addComponent(jlblBtn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTervehdysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTervehdysActionPerformed
        // TODO add your handling code here:
        String nimi; 
        int ika;
        double nimiika;
        String nimityhja = ""; 
        nimi = jtxtNimi.getText();
        String ikatyhja ="" ;
        
        try {  
        ika = Integer.parseInt(jtxtIka.getText());   
        }
        catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vain numeroita ikä kentässä kiitos. Virhe: " + e.getMessage() , "Virhe", JOptionPane.ERROR_MESSAGE);
        return;
        }
        
       try{
            nimiika = Double.parseDouble(jtxtNimi.getText());
            JOptionPane.showMessageDialog(null, "Nimessä ei saa olla numeroita: " , "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        catch (NumberFormatException e) {      
        }
       
        if(ika<=0 ){
            JOptionPane.showMessageDialog(null, "Ikä oltava positiivisia! Kiitos. Virhe: ");
            return;
        } else if (ika >120){
            JOptionPane.showMessageDialog(null, "Ikä on alle 120 vuotta! Kiitos. Virhe: ");
            return;
        } 
        
        if(nimi.equals("")){
            JOptionPane.showMessageDialog(null, "Nimessä ei oo mitää"  , "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultListModel dlm = new DefaultListModel();
        for (int i=0; i<=ika; i++){
            dlm.addElement("Hyvää syntymäpäivää:" + nimi + " " + i);
        }
        jlstReded.setModel(dlm);
    }//GEN-LAST:event_jbtnTervehdysActionPerformed

    private void jlblBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlblBtnActionPerformed
        // TODO add your handling code here:    
        

        String nimi; 
        int ika;
        double nimiika;
        
        nimi = jtxtNimi.getText();
        
        try { 
            
        ika = Integer.parseInt(jtxtIka.getText());   
        }
        
        catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vain numeroita ikä kentässä kiitos. Virhe: " + e.getMessage() , "Virhe", JOptionPane.ERROR_MESSAGE);
        
        return;
        }
       try{
                    nimiika = Double.parseDouble(jtxtNimi.getText());
                    JOptionPane.showMessageDialog(null, "Nimessä ei saa olla numeroita: " , "Virhe", JOptionPane.ERROR_MESSAGE);
                    return;
        } catch (NumberFormatException e) {
              
        }
        if(ika<=0 ){
                    JOptionPane.showMessageDialog(null, "Ikä oltava positiivisia! Kiitos. Virhe: ");
                    return;
        } else if (ika >120){
            JOptionPane.showMessageDialog(null, "Ikä on alle 120 vuotta! Kiitos. Virhe: ");
                    return;
        }
        if(nimi.equals("")){
            JOptionPane.showMessageDialog(null, "Nimessä ei oo mitää"  , "Virhe", JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        for (int i=0; i<=ika; i++){
        String appendText = ("Hyvää syntymäpäivää:" + nimi + " " + i+"\n");
        textArea.append(appendText);
        }
        
        
        
   
    }//GEN-LAST:event_jlblBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnTervehdys;
    private javax.swing.JButton jlblBtn;
    private javax.swing.JList<String> jlstReded;
    private javax.swing.JTextField jtxtIka;
    private javax.swing.JTextField jtxtNimi;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
