/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package noppapeli;

import java.util.Scanner;

/**
 *
 * @author denisbogdanov
 */
public class Teh16 extends javax.swing.JFrame {

    /**
     * Creates new form Teh16
     */
    public Teh16() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtpelaja = new javax.swing.JTextField();
        jtxtkone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtArea = new javax.swing.JTextArea();
        jbtnKylla = new javax.swing.JButton();
        jbntEi = new javax.swing.JButton();
        jBtnTyhjaa = new javax.swing.JButton();
        jtxtKtulos = new javax.swing.JTextField();
        jtxtPtulos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Noppapeli");

        jLabel2.setText("Pelaajan tulos:");

        jLabel3.setText("Koneen tulos:");

        jtxtpelaja.setText("0");

        jtxtkone.setText("0");
        jtxtkone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtkoneActionPerformed(evt);
            }
        });

        jLabel4.setText("Tämä ohjelma pelaa venttiä kahdella nopalla.");

        jLabel5.setText("Haluatko heitaa noppia?");

        jtxtArea.setColumns(20);
        jtxtArea.setRows(5);
        jScrollPane1.setViewportView(jtxtArea);

        jbtnKylla.setText("Kyllä");
        jbtnKylla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnKyllaActionPerformed(evt);
            }
        });

        jbntEi.setText("Ei");
        jbntEi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntEiActionPerformed(evt);
            }
        });

        jBtnTyhjaa.setText("Selkeä sivu");
        jBtnTyhjaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTyhjaaActionPerformed(evt);
            }
        });

        jtxtKtulos.setText("0");
        jtxtKtulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtKtulosActionPerformed(evt);
            }
        });

        jtxtPtulos.setText("0");
        jtxtPtulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPtulosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jtxtpelaja, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4)
                        .addGap(89, 89, 89)
                        .addComponent(jtxtkone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(62, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jbtnKylla)
                        .addGap(18, 18, 18)
                        .addComponent(jbntEi)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnTyhjaa)))
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtKtulos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPtulos, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtpelaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtkone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtKtulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPtulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbntEi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnKylla)
                        .addComponent(jBtnTyhjaa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnKyllaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnKyllaActionPerformed
        Noppa kone1 = new Noppa(6);
        Noppa kone2 = new Noppa(6);
        Noppa pelaaja1 = new Noppa(6);
        Noppa pelaaja2 = new Noppa(6);

        int pelaajaSumma = Integer.parseInt(jtxtpelaja.getText());
        int koneSumma = Integer.parseInt(jtxtkone.getText());
        int pelaatulos = Integer.parseInt(jtxtPtulos.getText());
        int konetulos = Integer.parseInt(jtxtKtulos.getText());
        String tulos;
        
        if (koneSumma == 0 || ((koneSumma < 21) && (koneSumma < pelaajaSumma))) {
            kone1.heita();
            kone2.heita();
            koneSumma += kone1.getArvo() + kone2.getArvo();
        }
        
        pelaaja1.heita();
        pelaaja2.heita();
        pelaajaSumma += pelaaja1.getArvo() + pelaaja2.getArvo();            
            
        String appendText = ( "Koneella on " + koneSumma + " pistettä." + "Pelaajalla on " + pelaajaSumma + " pistettä." + "\n" + "\n");
        jtxtArea.append(appendText);
        jtxtpelaja.setText(String.valueOf(pelaajaSumma));
        jtxtkone.setText(String.valueOf(koneSumma));
                          
        if((koneSumma > 21) && (pelaajaSumma > 21)){
             tulos = ( "Molemmat hävisivät!\n");
        jtxtArea.append(tulos);

        } else if ((koneSumma > 21) && (pelaajaSumma <=21)) { 
             tulos = ( "Pelaaja voitti!\n");
            pelaatulos +=1;
            jtxtPtulos.setText(String.valueOf(pelaatulos));
        jtxtArea.append(tulos);

        } else if ((koneSumma <= 21) && (pelaajaSumma > 21)) { 
             tulos = ( "Kone voitti!\n");
            konetulos +=1;
            jtxtKtulos.setText(String.valueOf(konetulos));
            jtxtArea.append(tulos);

        } else if (koneSumma >= pelaajaSumma && pelaajaSumma > 21) { 
             tulos = ( "Kone voitti!\n");
            konetulos +=1;
            jtxtKtulos.setText(String.valueOf(konetulos));
            jtxtArea.append(tulos);
        } else {
              tulos = ( "");
        jtxtArea.append(tulos);
        }

        if(pelaajaSumma>=21 || koneSumma>=21){
            pelaajaSumma = 0;
            koneSumma = 0;
            jtxtpelaja.setText(String.valueOf(pelaajaSumma));
        jtxtkone.setText(String.valueOf(koneSumma));
        }
    }//GEN-LAST:event_jbtnKyllaActionPerformed

    private void jtxtkoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtkoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtkoneActionPerformed

    private void jbntEiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntEiActionPerformed
        Noppa kone1 = new Noppa(6);
        Noppa kone2 = new Noppa(6);
        int pelaatulos = Integer.parseInt(jtxtPtulos.getText());
        int konetulos = Integer.parseInt(jtxtKtulos.getText());
        int pelaajaSumma = Integer.parseInt(jtxtpelaja.getText());
        int koneSumma = Integer.parseInt(jtxtkone.getText());
            
        if (koneSumma == 0 || ((koneSumma < 21) && (koneSumma < pelaajaSumma))) {
            kone1.heita();
            kone2.heita();
            koneSumma += kone1.getArvo() + kone2.getArvo();
        }

        String appendText = ( "Koneella on " + koneSumma + " pistettä." + "Pelaajalla on " + pelaajaSumma + " pistettä." + "\n" + "\n");
        jtxtArea.append(appendText);
        jtxtpelaja.setText(String.valueOf(pelaajaSumma));
        jtxtkone.setText(String.valueOf(koneSumma));

        if ((koneSumma > 21) && (pelaajaSumma <=21)) { // pelaaja voitti
            String tulos = ( "Pelaaja voitti!\n"+ "\n");
            pelaatulos +=1;
            pelaajaSumma = 0;
            koneSumma = 0;
            jtxtPtulos.setText(String.valueOf(pelaatulos));
            jtxtArea.append(tulos);
            jtxtpelaja.setText(String.valueOf(pelaajaSumma));
            jtxtkone.setText(String.valueOf(koneSumma));

        } else if ((koneSumma <= 21) && (pelaajaSumma > 21)) { //kone voitti
            String tulos = ( "Kone voitti!\n"+ "\n");
            konetulos +=1;
            jtxtKtulos.setText(String.valueOf(konetulos));
            jtxtArea.append(tulos);
            pelaajaSumma = 0;
            koneSumma = 0;
            jtxtpelaja.setText(String.valueOf(pelaajaSumma));
            jtxtkone.setText(String.valueOf(koneSumma));

        } else if (koneSumma > pelaajaSumma && pelaajaSumma < 21) { // kone voitti
            String tulos = ( "Kone voitti!\n"+ "\n");
            konetulos +=1;
            jtxtKtulos.setText(String.valueOf(konetulos));
            jtxtArea.append(tulos);
            pelaajaSumma = 0;
            koneSumma = 0;
            jtxtpelaja.setText(String.valueOf(pelaajaSumma));
            jtxtkone.setText(String.valueOf(koneSumma));
        
        } else if (koneSumma == pelaajaSumma && pelaajaSumma < 21) { // kone voitti
            String tulos = ( "Tili on sama!\n"+ "\n");
            jtxtArea.append(tulos);   
            pelaajaSumma = 0;
            koneSumma = 0;
            jtxtpelaja.setText(String.valueOf(pelaajaSumma));
            jtxtkone.setText(String.valueOf(koneSumma));
        }
        
        if ( (pelaajaSumma == 21)) { //kone voitti
            String tulos = ( "Pelaaja voitti!\n");
            jtxtArea.append(tulos);
            pelaatulos +=1;
            jtxtPtulos.setText(String.valueOf(pelaatulos));
            pelaajaSumma = 0;
            koneSumma = 0;
            jtxtpelaja.setText(String.valueOf(pelaajaSumma));
            jtxtkone.setText(String.valueOf(koneSumma));

        }
        
         if(koneSumma==21){
            String tulos = ( "Kone voitti!\n"+ "\n");
            konetulos +=1;
            pelaajaSumma = 0;
            koneSumma = 0;
            jtxtKtulos.setText(String.valueOf(konetulos));
            jtxtArea.append(tulos);
            jtxtpelaja.setText(String.valueOf(pelaajaSumma));
            jtxtkone.setText(String.valueOf(koneSumma));
        }
         
        else {
            String tulos = ( "");
            jtxtArea.append(tulos);
        }

        
        


     
    }//GEN-LAST:event_jbntEiActionPerformed

    private void jBtnTyhjaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTyhjaaActionPerformed
        // TODO add your handling code here:
        int pelaajaSumma = Integer.parseInt(jtxtpelaja.getText());
        int koneSumma = Integer.parseInt(jtxtkone.getText());
        
        pelaajaSumma = 0;
        koneSumma = 0;
        jtxtpelaja.setText(String.valueOf(pelaajaSumma));
        jtxtkone.setText(String.valueOf(koneSumma));
        jtxtArea.setText(null);
    }//GEN-LAST:event_jBtnTyhjaaActionPerformed

    private void jtxtPtulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPtulosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPtulosActionPerformed

    private void jtxtKtulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtKtulosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtKtulosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teh16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teh16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teh16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teh16.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teh16().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton jBtnTyhjaa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbntEi;
    private javax.swing.JButton jbtnKylla;
    private javax.swing.JTextArea jtxtArea;
    private javax.swing.JTextField jtxtKtulos;
    private javax.swing.JTextField jtxtPtulos;
    private javax.swing.JTextField jtxtkone;
    private javax.swing.JTextField jtxtpelaja;
    // End of variables declaration//GEN-END:variables
}
